config/routes.rb
Rooster::Application.routes.draw do

  #semi-static content
  get "about", to: 'info#about'
  get "contact", to: 'info#contact'
  get "license", to: 'info#license'

  #authentication
  devise_for :users, path_names: {sign_in: "login", sign_out: "logout"}

  #Target scaffold
  resources :targets

  #Homepage
  root to: 'targets#index'
end

app/models/target.rb
require 'net/http'
class Target < ActiveRecord::Base
  attr_accessible :host, :interval, :path, :next_run
  belongs_to :user
  validates :host, presence: true,
                   format: {with: /\A(\w|[\[.-])*\z/,
                            message: "only allows letters, numbers, _ and ."},
                   :allow_nil => false
  validates :interval, presence: true,
                       numericality: {only_integer: true,
                                      greater_than_or_equal_to: 15},
                       :allow_nil => false
  validate :path, :allow_nil => false
  validate :validate_interval_divisible_by_15


  after_initialize :init

  def init
    self.next_run = 0
    if self.path.nil? or self.path.empty?
      self.path = '/'
    end
  end

  def set_next_run(new_next_run)
    self.next_run = new_next_run
  end

  def wake_up
    puts Net::HTTP.get(self.host, self.path)
  end

  def validate_interval_divisible_by_15
     if self.interval.nil? or self.interval % 15 != 0
       errors.add(:interval, "must be divisible by 15")
     end
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  has_many :targets
  # attr_accessible :title, :body
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/info_controller.rb
class InfoController < ApplicationController
  def about
  end

  def contact
  end

  def license
  end
end

app/controllers/targets_controller.rb
class TargetsController < ApplicationController
  before_filter :authenticate_user!
  before_filter :setup_user

  def setup_user
    @user = current_user
  end
  # GET /targets
  # GET /targets.json
  def index
    @targets = @user.targets.all
    @numTargets = @targets.length
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @targets }
    end
  end

  # GET /targets/new
  # GET /targets/new.json
  def new

    @target = Target.new
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @target }
    end
  end

  # GET /targets/1/edit
  def edit
    @target = @user.targets.find(params[:id])
  end

  # POST /targets
  # POST /targets.json
  def create
    @target = @user.targets.build(params[:target])
    respond_to do |format|
      if @target.save
        format.html { redirect_to targets_url, notice: 'Target was successfully created.' }
        format.json { render json: @target, status: :created, location: @target }
      else
        format.html { render action: "new" }
        format.json { render json: @target.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /targets/1
  # PUT /targets/1.json
  def update
    @target = @user.targets.find(params[:id])
    respond_to do |format|
      if @target.update_attributes(params[:target])
        format.html { redirect_to targets_url, notice: 'Target was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @target.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /targets/1
  # DELETE /targets/1.json
  def destroy
    @target = @user.targets.find(params[:id])
    @target.destroy

    respond_to do |format|
      format.html { redirect_to targets_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/info_helper.rb
module InfoHelper
end

app/helpers/targets_helper.rb
module TargetsHelper
end

app/views/info/about.html.erb
<h1>Rooster</h1>
<p class="lead">The alarm clock for your shared-hosting web apps.</p>
<h3>What is Rooster?</h3>
<p>
  Rooster is a free service that visits web pages on a recurring schedule. You supply rooster with a list of “targets” -
  web addresses and schedules that determine when and where each site should be visited.
</p>
<h3>How can Rooster benefit my shared-hosting web application? </h3>
<p>
  Many shared-hosting VPS providers will put your application to sleep if it
  has no activity over a certain amount of time. This results in a significant “wake-up” time (usually 10 - 30 seconds)
  when a user tries to visit the site while it’s asleep. To prevent this, you can schedule Rooster to visit your site on
  a recurring interval to wake it up or stop it from sleeping altogether.
</p>
<h3>How often can Rooster visit my site? </h3>
<p>
  Currently, the minimum allowed interval between visits is 15 minutes. The
  maximum interval between visits is significantly greater than the time until the sun expands past the orbit of earth
  (in about 6 billion years). Intervals must be divisible by 15. Support for more complicated scheduling may be added
  later, but for now I don’t want to deal with timezones, days of the week, etc.
</p>
<h3>When will Rooster visit my site for the first time? </h3>
<p>
  Rooster will visit your site for the first time at the next quarter hour
  after you create a target. For example, let’s say you create a target at 9:33 AM that points to www.github.com\zcotter
  with an interval of 45 minutes. Rooster will first visit the site at 9:45 AM, then again at 10:30, 11:15, etc.
</p>
<h3>How does Rooster visit my site? </h3>
<p>
  Rooster uses Ruby’s net/http get function to “visit” web pages. This is
  similar to running wget or navigating to the page using your browser’s “view source” utility. The data retrieved
  from your site is discarded (although it may stick around in a log file for a little).
</p>
<h3>How can I report a bug, request a feature, add a feature myself, or contact you? </h3>
<p>
  You can email me at zach@zachcotter.com or open an issue on github at
  github.com/zcotter/Rooster. If you would like to contribute to Rooster yourself, you are more than welcome to fork my
  github repo and open a pull request.
</p>

app/views/info/contact.html.erb
<h1>Zach Cotter</h1>
<p>
  You can email me at zach@zachcotter.com or open an issue on github at github.com/zcotter/Rooster. If you would like to contribute to Rooster yourself, you are more than welcome to fork my github repo and open a pull request.
  <br/>
  <br/>
  <strong>Website: </strong><a href="http://www.zachcotter.com">zachcotter.com</a>
  <br/>
  <br/>
  <strong>Email: </strong><a href="mailto:zach@zachcotter.com">zach@zachcotter.com</a>
  <br/>
  <br/>
  <strong>Github: </strong><a href="http://github.com/zcotter">github.com/zcotter</a>
</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Rooster</title>
  <%= stylesheet_link_tag "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
<div class="navbar navbar-fixed-top">
  <div class="navbar-inner">
    <div class="container">
      <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </a>

      <div class="nav-collapse">
        <ul class="nav">
          <li><%= link_to "Rooster", about_path, :class => 'brand' %></li>

          <% if user_signed_in? %>
              <li>
                <p class="navbar-text" style="font-size: 100%;">
                  Logged in as <strong><%= current_user.email %></strong>.
                </p>
              </li>
              <li><a href="<%= targets_path %>">
                <i class="icon-home icon-white"></i> My Targets
              </a></li>
              <li><a href="<%= edit_user_registration_path %>">
                <i class="icon-cog icon-white"></i> Edit Profile
              </a></li>
              <li><a href="<%= destroy_user_session_path %>" data-method="delete" rel="nofollow">
                <i class="icon-circle-arrow-left icon-white"></i> Logout
              </a></li>
          <% else %>
              <li>
                <p class="navbar-text">
                  You are not logged in.
                </p>
              </li>
              <li><%= link_to "Sign up", new_user_registration_path %></li>
              <li><%= link_to "Login", new_user_session_path %></li>
          <% end %>
          <li><%= link_to "What is Rooster?", about_path %></li>
        </ul>
      </div>
    </div>
  </div>
</div>
<div class="container-fluid">
  <% flash.each do |name, msg| %>
      <div id="<%= "flash_#{name}" %>" class="alert alert-success">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        <%= msg %>
      </div>
  <% end %>

  <%= yield %>
</div>
<div class="footer">
  <br/>

  <p class="text-center" style="border-top-style: solid;">
    <br/>

  <div class="row-fluid">
    <div class="span3"></div>
    <%= link_to "About", about_path, :class => "span2 text-left" %>
    <%= link_to "Contact", contact_path, :class => "span2 text-center" %>
    <%= link_to "License", license_path, :class => "span2 text-right" %>
    <div class="span3"></div>
  </div>
  <div class="text-center">
    Rooster, by <%= link_to "Zach Cotter", "http://www.zachcotter.com" %>, is licensed under
    the <%= link_to "Creative Commons Attribution 3.0 Unported License", license_path %>
  </div>
  </p>
  <br/>
  <br/>
  <br/>
</div>
<!-- Piwik -->
<script type="text/javascript">
    var _paq = _paq || [];
    _paq.push(["setDocumentTitle", document.domain + "/" + document.title]);
    _paq.push(["setCookieDomain", "*.roosterapp.herokuapp.com"]);
    _paq.push(["setDomains", ["*.roosterapp.herokuapp.com", "*.rooster.zachcotter.com"]]);
    _paq.push(["trackPageView"]);
    _paq.push(["enableLinkTracking"]);

    (function () {
        var u = (("https:" == document.location.protocol) ? "https" : "http") + "://www.zachcotter.com/piwik/";
        _paq.push(["setTrackerUrl", u + "piwik.php"]);
        _paq.push(["setSiteId", "2"]);
        var d = document, g = d.createElement("script"), s = d.getElementsByTagName("script")[0];
        g.type = "text/javascript";
        g.defer = true;
        g.async = true;
        g.src = u + "piwik.js";
        s.parentNode.insertBefore(g, s);
    })();
</script>
<!-- Piwik Image Tracker -->
<noscript>
  <img src="http://www.zachcotter.com/piwik/piwik.php?idsite=2&amp;rec=1" style="border:0" alt=""/>
</noscript>
<!-- End Piwik -->
<!-- End Piwik Code -->
</body>
</html>

app/views/targets/_form.html.erb
<%= form_for(@target) do |f| %>
    <% if @target.errors.any? %>
        <div class="well" id="error_explanation">
          <h2><%= pluralize(@target.errors.count, "error") %> prohibited this target from being saved:</h2>

          <ul>
            <% @target.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
    <% end %>
    <p>
    Rooster should visit the domain
    <%= f.text_field :host %>
     at path
      <%= f.text_field :path %>
     every
      <%= f.number_field :interval, :min => 15, :value => @target.interval, :step => 15, :style => "width: 10%;" %>
      minutes.
    </p>

    <div class="actions">
      <%= f.submit :class => "btn btn-large btn-danger" %>
    </div>
<% end %>

app/views/targets/edit.html.erb
<h1>Edit Target</h1>

<%= render 'form' %>

<%= link_to 'Back', targets_path, :class => "btn btn-danger"  %>

app/views/targets/index.html.erb
<h1>Targets</h1>
<p class="lead">
  <% if @numTargets < 1 %>
  You have no targets! Click the button below to create one.
  <% else %>
  Each of the following addresses will be visited repeatedly on the specified interval.
  <% end %>
</p>
<% counter = 0 %>
<% @targets.each do |target| %>
    <% counter += 1 %>
    <p>
      <%= "#{counter}. #{target.host}#{target.path} will be visited every #{target.interval} minutes." %>
      <a href="<%= edit_target_path(target) %>" class="btn btn-danger">
        <i class="icon-edit icon-white"></i>
      </a>
      <a href="<%= target_path(target) %>" data-confirm="Are you sure you want to delete this target?" data-method="delete" rel="nofollow" class="btn btn-danger">
        <i class="icon-trash icon-white"></i>
      </a>
    </p>

<% end %>


<br/>
<a href="<%= new_target_path %>" class="btn btn-large btn-danger">
  <i class="icon-plus icon-white"> </i>
  &nbsp;Add Another Target
</a>

app/views/targets/new.html.erb
<h1>Add another target</h1>

<%= render 'form' %>

<%= link_to 'Cancel', targets_path, :class => "btn btn-danger"  %>